AWSTemplateFormatVersion: '2010-09-09'
Description: 'HDPS (1/6) - S3 Storage Buckets'

Parameters:
  EnvironmentName:
    Type: String
    Default: dev

Resources:
  PredictionResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${EnvironmentName}-results-${AWS::AccountId}-${AWS::Region}'

  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${EnvironmentName}-frontend-${AWS::AccountId}-${AWS::Region}'

Outputs:
  ResultsBucketName:
    Value: !Ref PredictionResultsBucket
    Export:
      Name: hdps-ResultsBucketName

  FrontendBucketName:
    Value: !Ref FrontendBucket
    Export:
      Name: hdps-FrontendBucketName

  FrontendBucketDomainName:
    Value: !GetAtt FrontendBucket.RegionalDomainName
    Export:
      Name: hdps-FrontendBucketDomainName
