AWSTemplateFormatVersion: '2010-09-09'

Resources:
  TestDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t3.micro
      Engine: mysql
      MasterUsername: admin
      MasterUserPassword: Admin123!
      AllocatedStorage: 20
      PubliclyAccessible: true